// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newKthenaChatSession(db *gorm.DB, opts ...gen.DOOption) kthenaChatSession {
	_kthenaChatSession := kthenaChatSession{}

	_kthenaChatSession.kthenaChatSessionDo.UseDB(db, opts...)
	_kthenaChatSession.kthenaChatSessionDo.UseModel(&model.KthenaChatSession{})

	tableName := _kthenaChatSession.kthenaChatSessionDo.TableName()
	_kthenaChatSession.ALL = field.NewAsterisk(tableName)
	_kthenaChatSession.TurnLease = field.NewString(tableName, "turn_lease")
	_kthenaChatSession.TurnExpiresAt = field.NewTime(tableName, "turn_expires_at")
	_kthenaChatSession.ID = field.NewUint(tableName, "id")
	_kthenaChatSession.UserID = field.NewUint(tableName, "user_id")
	_kthenaChatSession.AccountID = field.NewUint(tableName, "account_id")
	_kthenaChatSession.Username = field.NewString(tableName, "username")
	_kthenaChatSession.Namespace = field.NewString(tableName, "namespace")
	_kthenaChatSession.ServiceName = field.NewString(tableName, "service_name")
	_kthenaChatSession.ModelName = field.NewString(tableName, "model_name")
	_kthenaChatSession.BackendType = field.NewString(tableName, "backend_type")
	_kthenaChatSession.ClientSessionID = field.NewString(tableName, "client_session_id")
	_kthenaChatSession.Title = field.NewString(tableName, "title")
	_kthenaChatSession.MessageCount = field.NewInt(tableName, "message_count")
	_kthenaChatSession.LastMessageAt = field.NewTime(tableName, "last_message_at")
	_kthenaChatSession.CreatedAt = field.NewTime(tableName, "created_at")
	_kthenaChatSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_kthenaChatSession.fillFieldMap()

	return _kthenaChatSession
}

type kthenaChatSession struct {
	kthenaChatSessionDo kthenaChatSessionDo

	ALL             field.Asterisk
	TurnLease       field.String
	TurnExpiresAt   field.Time
	ID              field.Uint
	UserID          field.Uint   // 会话所属用户ID
	AccountID       field.Uint   // 会话所属账户ID
	Username        field.String // 创建会话时的用户名快照
	Namespace       field.String // 模型部署命名空间
	ServiceName     field.String // ModelServing名称
	ModelName       field.String // 路由模型名快照
	BackendType     field.String // 推理后端快照
	ClientSessionID field.String // 客户端会话UUID
	Title           field.String // 会话标题
	MessageCount    field.Int    // 消息数
	LastMessageAt   field.Time   // 最后一条消息时间
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (k kthenaChatSession) Table(newTableName string) *kthenaChatSession {
	k.kthenaChatSessionDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kthenaChatSession) As(alias string) *kthenaChatSession {
	k.kthenaChatSessionDo.DO = *(k.kthenaChatSessionDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kthenaChatSession) updateTableName(table string) *kthenaChatSession {
	k.ALL = field.NewAsterisk(table)
	k.TurnLease = field.NewString(table, "turn_lease")
	k.TurnExpiresAt = field.NewTime(table, "turn_expires_at")
	k.ID = field.NewUint(table, "id")
	k.UserID = field.NewUint(table, "user_id")
	k.AccountID = field.NewUint(table, "account_id")
	k.Username = field.NewString(table, "username")
	k.Namespace = field.NewString(table, "namespace")
	k.ServiceName = field.NewString(table, "service_name")
	k.ModelName = field.NewString(table, "model_name")
	k.BackendType = field.NewString(table, "backend_type")
	k.ClientSessionID = field.NewString(table, "client_session_id")
	k.Title = field.NewString(table, "title")
	k.MessageCount = field.NewInt(table, "message_count")
	k.LastMessageAt = field.NewTime(table, "last_message_at")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *kthenaChatSession) WithContext(ctx context.Context) IKthenaChatSessionDo {
	return k.kthenaChatSessionDo.WithContext(ctx)
}

func (k kthenaChatSession) TableName() string { return k.kthenaChatSessionDo.TableName() }

func (k kthenaChatSession) Alias() string { return k.kthenaChatSessionDo.Alias() }

func (k kthenaChatSession) Columns(cols ...field.Expr) gen.Columns {
	return k.kthenaChatSessionDo.Columns(cols...)
}

func (k *kthenaChatSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kthenaChatSession) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 16)
	k.fieldMap["turn_lease"] = k.TurnLease
	k.fieldMap["turn_expires_at"] = k.TurnExpiresAt
	k.fieldMap["id"] = k.ID
	k.fieldMap["user_id"] = k.UserID
	k.fieldMap["account_id"] = k.AccountID
	k.fieldMap["username"] = k.Username
	k.fieldMap["namespace"] = k.Namespace
	k.fieldMap["service_name"] = k.ServiceName
	k.fieldMap["model_name"] = k.ModelName
	k.fieldMap["backend_type"] = k.BackendType
	k.fieldMap["client_session_id"] = k.ClientSessionID
	k.fieldMap["title"] = k.Title
	k.fieldMap["message_count"] = k.MessageCount
	k.fieldMap["last_message_at"] = k.LastMessageAt
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k kthenaChatSession) clone(db *gorm.DB) kthenaChatSession {
	k.kthenaChatSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kthenaChatSession) replaceDB(db *gorm.DB) kthenaChatSession {
	k.kthenaChatSessionDo.ReplaceDB(db)
	return k
}

type kthenaChatSessionDo struct{ gen.DO }

type IKthenaChatSessionDo interface {
	gen.SubQuery
	Debug() IKthenaChatSessionDo
	WithContext(ctx context.Context) IKthenaChatSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKthenaChatSessionDo
	WriteDB() IKthenaChatSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKthenaChatSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKthenaChatSessionDo
	Not(conds ...gen.Condition) IKthenaChatSessionDo
	Or(conds ...gen.Condition) IKthenaChatSessionDo
	Select(conds ...field.Expr) IKthenaChatSessionDo
	Where(conds ...gen.Condition) IKthenaChatSessionDo
	Order(conds ...field.Expr) IKthenaChatSessionDo
	Distinct(cols ...field.Expr) IKthenaChatSessionDo
	Omit(cols ...field.Expr) IKthenaChatSessionDo
	Join(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo
	Group(cols ...field.Expr) IKthenaChatSessionDo
	Having(conds ...gen.Condition) IKthenaChatSessionDo
	Limit(limit int) IKthenaChatSessionDo
	Offset(offset int) IKthenaChatSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaChatSessionDo
	Unscoped() IKthenaChatSessionDo
	Create(values ...*model.KthenaChatSession) error
	CreateInBatches(values []*model.KthenaChatSession, batchSize int) error
	Save(values ...*model.KthenaChatSession) error
	First() (*model.KthenaChatSession, error)
	Take() (*model.KthenaChatSession, error)
	Last() (*model.KthenaChatSession, error)
	Find() ([]*model.KthenaChatSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaChatSession, err error)
	FindInBatches(result *[]*model.KthenaChatSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KthenaChatSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKthenaChatSessionDo
	Assign(attrs ...field.AssignExpr) IKthenaChatSessionDo
	Joins(fields ...field.RelationField) IKthenaChatSessionDo
	Preload(fields ...field.RelationField) IKthenaChatSessionDo
	FirstOrInit() (*model.KthenaChatSession, error)
	FirstOrCreate() (*model.KthenaChatSession, error)
	FindByPage(offset int, limit int) (result []*model.KthenaChatSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKthenaChatSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kthenaChatSessionDo) Debug() IKthenaChatSessionDo {
	return k.withDO(k.DO.Debug())
}

func (k kthenaChatSessionDo) WithContext(ctx context.Context) IKthenaChatSessionDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kthenaChatSessionDo) ReadDB() IKthenaChatSessionDo {
	return k.Clauses(dbresolver.Read)
}

func (k kthenaChatSessionDo) WriteDB() IKthenaChatSessionDo {
	return k.Clauses(dbresolver.Write)
}

func (k kthenaChatSessionDo) Session(config *gorm.Session) IKthenaChatSessionDo {
	return k.withDO(k.DO.Session(config))
}

func (k kthenaChatSessionDo) Clauses(conds ...clause.Expression) IKthenaChatSessionDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kthenaChatSessionDo) Returning(value interface{}, columns ...string) IKthenaChatSessionDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kthenaChatSessionDo) Not(conds ...gen.Condition) IKthenaChatSessionDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kthenaChatSessionDo) Or(conds ...gen.Condition) IKthenaChatSessionDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kthenaChatSessionDo) Select(conds ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kthenaChatSessionDo) Where(conds ...gen.Condition) IKthenaChatSessionDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kthenaChatSessionDo) Order(conds ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kthenaChatSessionDo) Distinct(cols ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kthenaChatSessionDo) Omit(cols ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kthenaChatSessionDo) Join(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kthenaChatSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kthenaChatSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kthenaChatSessionDo) Group(cols ...field.Expr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kthenaChatSessionDo) Having(conds ...gen.Condition) IKthenaChatSessionDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kthenaChatSessionDo) Limit(limit int) IKthenaChatSessionDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kthenaChatSessionDo) Offset(offset int) IKthenaChatSessionDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kthenaChatSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaChatSessionDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kthenaChatSessionDo) Unscoped() IKthenaChatSessionDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kthenaChatSessionDo) Create(values ...*model.KthenaChatSession) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kthenaChatSessionDo) CreateInBatches(values []*model.KthenaChatSession, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kthenaChatSessionDo) Save(values ...*model.KthenaChatSession) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kthenaChatSessionDo) First() (*model.KthenaChatSession, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatSession), nil
	}
}

func (k kthenaChatSessionDo) Take() (*model.KthenaChatSession, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatSession), nil
	}
}

func (k kthenaChatSessionDo) Last() (*model.KthenaChatSession, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatSession), nil
	}
}

func (k kthenaChatSessionDo) Find() ([]*model.KthenaChatSession, error) {
	result, err := k.DO.Find()
	return result.([]*model.KthenaChatSession), err
}

func (k kthenaChatSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaChatSession, err error) {
	buf := make([]*model.KthenaChatSession, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kthenaChatSessionDo) FindInBatches(result *[]*model.KthenaChatSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kthenaChatSessionDo) Attrs(attrs ...field.AssignExpr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kthenaChatSessionDo) Assign(attrs ...field.AssignExpr) IKthenaChatSessionDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kthenaChatSessionDo) Joins(fields ...field.RelationField) IKthenaChatSessionDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kthenaChatSessionDo) Preload(fields ...field.RelationField) IKthenaChatSessionDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kthenaChatSessionDo) FirstOrInit() (*model.KthenaChatSession, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatSession), nil
	}
}

func (k kthenaChatSessionDo) FirstOrCreate() (*model.KthenaChatSession, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatSession), nil
	}
}

func (k kthenaChatSessionDo) FindByPage(offset int, limit int) (result []*model.KthenaChatSession, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kthenaChatSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kthenaChatSessionDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kthenaChatSessionDo) Delete(models ...*model.KthenaChatSession) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kthenaChatSessionDo) withDO(do gen.Dao) *kthenaChatSessionDo {
	k.DO = *do.(*gen.DO)
	return k
}
