// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newKthenaInferenceTemplate(db *gorm.DB, opts ...gen.DOOption) kthenaInferenceTemplate {
	_kthenaInferenceTemplate := kthenaInferenceTemplate{}

	_kthenaInferenceTemplate.kthenaInferenceTemplateDo.UseDB(db, opts...)
	_kthenaInferenceTemplate.kthenaInferenceTemplateDo.UseModel(&model.KthenaInferenceTemplate{})

	tableName := _kthenaInferenceTemplate.kthenaInferenceTemplateDo.TableName()
	_kthenaInferenceTemplate.ALL = field.NewAsterisk(tableName)
	_kthenaInferenceTemplate.ID = field.NewUint(tableName, "id")
	_kthenaInferenceTemplate.CreatedAt = field.NewTime(tableName, "created_at")
	_kthenaInferenceTemplate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_kthenaInferenceTemplate.DeletedAt = field.NewField(tableName, "deleted_at")
	_kthenaInferenceTemplate.UserID = field.NewUint(tableName, "user_id")
	_kthenaInferenceTemplate.AccountID = field.NewUint(tableName, "account_id")
	_kthenaInferenceTemplate.Name = field.NewString(tableName, "name")
	_kthenaInferenceTemplate.Description = field.NewString(tableName, "description")
	_kthenaInferenceTemplate.Config = field.NewField(tableName, "config")

	_kthenaInferenceTemplate.fillFieldMap()

	return _kthenaInferenceTemplate
}

type kthenaInferenceTemplate struct {
	kthenaInferenceTemplateDo kthenaInferenceTemplateDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	UserID      field.Uint   // 模板所属用户ID
	AccountID   field.Uint   // 模板所属账户ID
	Name        field.String // 模板名称
	Description field.String // 模板说明
	Config      field.Field  // 模型部署表单配置

	fieldMap map[string]field.Expr
}

func (k kthenaInferenceTemplate) Table(newTableName string) *kthenaInferenceTemplate {
	k.kthenaInferenceTemplateDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kthenaInferenceTemplate) As(alias string) *kthenaInferenceTemplate {
	k.kthenaInferenceTemplateDo.DO = *(k.kthenaInferenceTemplateDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kthenaInferenceTemplate) updateTableName(table string) *kthenaInferenceTemplate {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint(table, "id")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.DeletedAt = field.NewField(table, "deleted_at")
	k.UserID = field.NewUint(table, "user_id")
	k.AccountID = field.NewUint(table, "account_id")
	k.Name = field.NewString(table, "name")
	k.Description = field.NewString(table, "description")
	k.Config = field.NewField(table, "config")

	k.fillFieldMap()

	return k
}

func (k *kthenaInferenceTemplate) WithContext(ctx context.Context) IKthenaInferenceTemplateDo {
	return k.kthenaInferenceTemplateDo.WithContext(ctx)
}

func (k kthenaInferenceTemplate) TableName() string { return k.kthenaInferenceTemplateDo.TableName() }

func (k kthenaInferenceTemplate) Alias() string { return k.kthenaInferenceTemplateDo.Alias() }

func (k kthenaInferenceTemplate) Columns(cols ...field.Expr) gen.Columns {
	return k.kthenaInferenceTemplateDo.Columns(cols...)
}

func (k *kthenaInferenceTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kthenaInferenceTemplate) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 9)
	k.fieldMap["id"] = k.ID
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["deleted_at"] = k.DeletedAt
	k.fieldMap["user_id"] = k.UserID
	k.fieldMap["account_id"] = k.AccountID
	k.fieldMap["name"] = k.Name
	k.fieldMap["description"] = k.Description
	k.fieldMap["config"] = k.Config
}

func (k kthenaInferenceTemplate) clone(db *gorm.DB) kthenaInferenceTemplate {
	k.kthenaInferenceTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kthenaInferenceTemplate) replaceDB(db *gorm.DB) kthenaInferenceTemplate {
	k.kthenaInferenceTemplateDo.ReplaceDB(db)
	return k
}

type kthenaInferenceTemplateDo struct{ gen.DO }

type IKthenaInferenceTemplateDo interface {
	gen.SubQuery
	Debug() IKthenaInferenceTemplateDo
	WithContext(ctx context.Context) IKthenaInferenceTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKthenaInferenceTemplateDo
	WriteDB() IKthenaInferenceTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKthenaInferenceTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKthenaInferenceTemplateDo
	Not(conds ...gen.Condition) IKthenaInferenceTemplateDo
	Or(conds ...gen.Condition) IKthenaInferenceTemplateDo
	Select(conds ...field.Expr) IKthenaInferenceTemplateDo
	Where(conds ...gen.Condition) IKthenaInferenceTemplateDo
	Order(conds ...field.Expr) IKthenaInferenceTemplateDo
	Distinct(cols ...field.Expr) IKthenaInferenceTemplateDo
	Omit(cols ...field.Expr) IKthenaInferenceTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo
	Group(cols ...field.Expr) IKthenaInferenceTemplateDo
	Having(conds ...gen.Condition) IKthenaInferenceTemplateDo
	Limit(limit int) IKthenaInferenceTemplateDo
	Offset(offset int) IKthenaInferenceTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaInferenceTemplateDo
	Unscoped() IKthenaInferenceTemplateDo
	Create(values ...*model.KthenaInferenceTemplate) error
	CreateInBatches(values []*model.KthenaInferenceTemplate, batchSize int) error
	Save(values ...*model.KthenaInferenceTemplate) error
	First() (*model.KthenaInferenceTemplate, error)
	Take() (*model.KthenaInferenceTemplate, error)
	Last() (*model.KthenaInferenceTemplate, error)
	Find() ([]*model.KthenaInferenceTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaInferenceTemplate, err error)
	FindInBatches(result *[]*model.KthenaInferenceTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KthenaInferenceTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKthenaInferenceTemplateDo
	Assign(attrs ...field.AssignExpr) IKthenaInferenceTemplateDo
	Joins(fields ...field.RelationField) IKthenaInferenceTemplateDo
	Preload(fields ...field.RelationField) IKthenaInferenceTemplateDo
	FirstOrInit() (*model.KthenaInferenceTemplate, error)
	FirstOrCreate() (*model.KthenaInferenceTemplate, error)
	FindByPage(offset int, limit int) (result []*model.KthenaInferenceTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKthenaInferenceTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kthenaInferenceTemplateDo) Debug() IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Debug())
}

func (k kthenaInferenceTemplateDo) WithContext(ctx context.Context) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kthenaInferenceTemplateDo) ReadDB() IKthenaInferenceTemplateDo {
	return k.Clauses(dbresolver.Read)
}

func (k kthenaInferenceTemplateDo) WriteDB() IKthenaInferenceTemplateDo {
	return k.Clauses(dbresolver.Write)
}

func (k kthenaInferenceTemplateDo) Session(config *gorm.Session) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Session(config))
}

func (k kthenaInferenceTemplateDo) Clauses(conds ...clause.Expression) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kthenaInferenceTemplateDo) Returning(value interface{}, columns ...string) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kthenaInferenceTemplateDo) Not(conds ...gen.Condition) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kthenaInferenceTemplateDo) Or(conds ...gen.Condition) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kthenaInferenceTemplateDo) Select(conds ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kthenaInferenceTemplateDo) Where(conds ...gen.Condition) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kthenaInferenceTemplateDo) Order(conds ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kthenaInferenceTemplateDo) Distinct(cols ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kthenaInferenceTemplateDo) Omit(cols ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kthenaInferenceTemplateDo) Join(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kthenaInferenceTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kthenaInferenceTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kthenaInferenceTemplateDo) Group(cols ...field.Expr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kthenaInferenceTemplateDo) Having(conds ...gen.Condition) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kthenaInferenceTemplateDo) Limit(limit int) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kthenaInferenceTemplateDo) Offset(offset int) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kthenaInferenceTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kthenaInferenceTemplateDo) Unscoped() IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kthenaInferenceTemplateDo) Create(values ...*model.KthenaInferenceTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kthenaInferenceTemplateDo) CreateInBatches(values []*model.KthenaInferenceTemplate, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kthenaInferenceTemplateDo) Save(values ...*model.KthenaInferenceTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kthenaInferenceTemplateDo) First() (*model.KthenaInferenceTemplate, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaInferenceTemplate), nil
	}
}

func (k kthenaInferenceTemplateDo) Take() (*model.KthenaInferenceTemplate, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaInferenceTemplate), nil
	}
}

func (k kthenaInferenceTemplateDo) Last() (*model.KthenaInferenceTemplate, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaInferenceTemplate), nil
	}
}

func (k kthenaInferenceTemplateDo) Find() ([]*model.KthenaInferenceTemplate, error) {
	result, err := k.DO.Find()
	return result.([]*model.KthenaInferenceTemplate), err
}

func (k kthenaInferenceTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaInferenceTemplate, err error) {
	buf := make([]*model.KthenaInferenceTemplate, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kthenaInferenceTemplateDo) FindInBatches(result *[]*model.KthenaInferenceTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kthenaInferenceTemplateDo) Attrs(attrs ...field.AssignExpr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kthenaInferenceTemplateDo) Assign(attrs ...field.AssignExpr) IKthenaInferenceTemplateDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kthenaInferenceTemplateDo) Joins(fields ...field.RelationField) IKthenaInferenceTemplateDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kthenaInferenceTemplateDo) Preload(fields ...field.RelationField) IKthenaInferenceTemplateDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kthenaInferenceTemplateDo) FirstOrInit() (*model.KthenaInferenceTemplate, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaInferenceTemplate), nil
	}
}

func (k kthenaInferenceTemplateDo) FirstOrCreate() (*model.KthenaInferenceTemplate, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaInferenceTemplate), nil
	}
}

func (k kthenaInferenceTemplateDo) FindByPage(offset int, limit int) (result []*model.KthenaInferenceTemplate, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kthenaInferenceTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kthenaInferenceTemplateDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kthenaInferenceTemplateDo) Delete(models ...*model.KthenaInferenceTemplate) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kthenaInferenceTemplateDo) withDO(do gen.Dao) *kthenaInferenceTemplateDo {
	k.DO = *do.(*gen.DO)
	return k
}
