// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newKthenaChatMessage(db *gorm.DB, opts ...gen.DOOption) kthenaChatMessage {
	_kthenaChatMessage := kthenaChatMessage{}

	_kthenaChatMessage.kthenaChatMessageDo.UseDB(db, opts...)
	_kthenaChatMessage.kthenaChatMessageDo.UseModel(&model.KthenaChatMessage{})

	tableName := _kthenaChatMessage.kthenaChatMessageDo.TableName()
	_kthenaChatMessage.ALL = field.NewAsterisk(tableName)
	_kthenaChatMessage.RequestHash = field.NewString(tableName, "request_hash")
	_kthenaChatMessage.ID = field.NewUint(tableName, "id")
	_kthenaChatMessage.SessionID = field.NewUint(tableName, "session_id")
	_kthenaChatMessage.Sequence = field.NewInt(tableName, "sequence")
	_kthenaChatMessage.Role = field.NewString(tableName, "role")
	_kthenaChatMessage.Content = field.NewString(tableName, "content")
	_kthenaChatMessage.ClientTurnID = field.NewString(tableName, "client_turn_id")
	_kthenaChatMessage.ResponseJSON = field.NewField(tableName, "response_json")
	_kthenaChatMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_kthenaChatMessage.fillFieldMap()

	return _kthenaChatMessage
}

type kthenaChatMessage struct {
	kthenaChatMessageDo kthenaChatMessageDo

	ALL          field.Asterisk
	RequestHash  field.String
	ID           field.Uint
	SessionID    field.Uint   // 会话ID
	Sequence     field.Int    // 会话内消息顺序
	Role         field.String // OpenAI消息角色
	Content      field.String // 消息正文
	ClientTurnID field.String // 客户端幂等请求ID
	ResponseJSON field.Field  // 助手消息对应的原始模型响应
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (k kthenaChatMessage) Table(newTableName string) *kthenaChatMessage {
	k.kthenaChatMessageDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kthenaChatMessage) As(alias string) *kthenaChatMessage {
	k.kthenaChatMessageDo.DO = *(k.kthenaChatMessageDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kthenaChatMessage) updateTableName(table string) *kthenaChatMessage {
	k.ALL = field.NewAsterisk(table)
	k.RequestHash = field.NewString(table, "request_hash")
	k.ID = field.NewUint(table, "id")
	k.SessionID = field.NewUint(table, "session_id")
	k.Sequence = field.NewInt(table, "sequence")
	k.Role = field.NewString(table, "role")
	k.Content = field.NewString(table, "content")
	k.ClientTurnID = field.NewString(table, "client_turn_id")
	k.ResponseJSON = field.NewField(table, "response_json")
	k.CreatedAt = field.NewTime(table, "created_at")

	k.fillFieldMap()

	return k
}

func (k *kthenaChatMessage) WithContext(ctx context.Context) IKthenaChatMessageDo {
	return k.kthenaChatMessageDo.WithContext(ctx)
}

func (k kthenaChatMessage) TableName() string { return k.kthenaChatMessageDo.TableName() }

func (k kthenaChatMessage) Alias() string { return k.kthenaChatMessageDo.Alias() }

func (k kthenaChatMessage) Columns(cols ...field.Expr) gen.Columns {
	return k.kthenaChatMessageDo.Columns(cols...)
}

func (k *kthenaChatMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kthenaChatMessage) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 9)
	k.fieldMap["request_hash"] = k.RequestHash
	k.fieldMap["id"] = k.ID
	k.fieldMap["session_id"] = k.SessionID
	k.fieldMap["sequence"] = k.Sequence
	k.fieldMap["role"] = k.Role
	k.fieldMap["content"] = k.Content
	k.fieldMap["client_turn_id"] = k.ClientTurnID
	k.fieldMap["response_json"] = k.ResponseJSON
	k.fieldMap["created_at"] = k.CreatedAt
}

func (k kthenaChatMessage) clone(db *gorm.DB) kthenaChatMessage {
	k.kthenaChatMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kthenaChatMessage) replaceDB(db *gorm.DB) kthenaChatMessage {
	k.kthenaChatMessageDo.ReplaceDB(db)
	return k
}

type kthenaChatMessageDo struct{ gen.DO }

type IKthenaChatMessageDo interface {
	gen.SubQuery
	Debug() IKthenaChatMessageDo
	WithContext(ctx context.Context) IKthenaChatMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKthenaChatMessageDo
	WriteDB() IKthenaChatMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKthenaChatMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKthenaChatMessageDo
	Not(conds ...gen.Condition) IKthenaChatMessageDo
	Or(conds ...gen.Condition) IKthenaChatMessageDo
	Select(conds ...field.Expr) IKthenaChatMessageDo
	Where(conds ...gen.Condition) IKthenaChatMessageDo
	Order(conds ...field.Expr) IKthenaChatMessageDo
	Distinct(cols ...field.Expr) IKthenaChatMessageDo
	Omit(cols ...field.Expr) IKthenaChatMessageDo
	Join(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo
	Group(cols ...field.Expr) IKthenaChatMessageDo
	Having(conds ...gen.Condition) IKthenaChatMessageDo
	Limit(limit int) IKthenaChatMessageDo
	Offset(offset int) IKthenaChatMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaChatMessageDo
	Unscoped() IKthenaChatMessageDo
	Create(values ...*model.KthenaChatMessage) error
	CreateInBatches(values []*model.KthenaChatMessage, batchSize int) error
	Save(values ...*model.KthenaChatMessage) error
	First() (*model.KthenaChatMessage, error)
	Take() (*model.KthenaChatMessage, error)
	Last() (*model.KthenaChatMessage, error)
	Find() ([]*model.KthenaChatMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaChatMessage, err error)
	FindInBatches(result *[]*model.KthenaChatMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KthenaChatMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKthenaChatMessageDo
	Assign(attrs ...field.AssignExpr) IKthenaChatMessageDo
	Joins(fields ...field.RelationField) IKthenaChatMessageDo
	Preload(fields ...field.RelationField) IKthenaChatMessageDo
	FirstOrInit() (*model.KthenaChatMessage, error)
	FirstOrCreate() (*model.KthenaChatMessage, error)
	FindByPage(offset int, limit int) (result []*model.KthenaChatMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKthenaChatMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kthenaChatMessageDo) Debug() IKthenaChatMessageDo {
	return k.withDO(k.DO.Debug())
}

func (k kthenaChatMessageDo) WithContext(ctx context.Context) IKthenaChatMessageDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kthenaChatMessageDo) ReadDB() IKthenaChatMessageDo {
	return k.Clauses(dbresolver.Read)
}

func (k kthenaChatMessageDo) WriteDB() IKthenaChatMessageDo {
	return k.Clauses(dbresolver.Write)
}

func (k kthenaChatMessageDo) Session(config *gorm.Session) IKthenaChatMessageDo {
	return k.withDO(k.DO.Session(config))
}

func (k kthenaChatMessageDo) Clauses(conds ...clause.Expression) IKthenaChatMessageDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kthenaChatMessageDo) Returning(value interface{}, columns ...string) IKthenaChatMessageDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kthenaChatMessageDo) Not(conds ...gen.Condition) IKthenaChatMessageDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kthenaChatMessageDo) Or(conds ...gen.Condition) IKthenaChatMessageDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kthenaChatMessageDo) Select(conds ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kthenaChatMessageDo) Where(conds ...gen.Condition) IKthenaChatMessageDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kthenaChatMessageDo) Order(conds ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kthenaChatMessageDo) Distinct(cols ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kthenaChatMessageDo) Omit(cols ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kthenaChatMessageDo) Join(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kthenaChatMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kthenaChatMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kthenaChatMessageDo) Group(cols ...field.Expr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kthenaChatMessageDo) Having(conds ...gen.Condition) IKthenaChatMessageDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kthenaChatMessageDo) Limit(limit int) IKthenaChatMessageDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kthenaChatMessageDo) Offset(offset int) IKthenaChatMessageDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kthenaChatMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKthenaChatMessageDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kthenaChatMessageDo) Unscoped() IKthenaChatMessageDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kthenaChatMessageDo) Create(values ...*model.KthenaChatMessage) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kthenaChatMessageDo) CreateInBatches(values []*model.KthenaChatMessage, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kthenaChatMessageDo) Save(values ...*model.KthenaChatMessage) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kthenaChatMessageDo) First() (*model.KthenaChatMessage, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatMessage), nil
	}
}

func (k kthenaChatMessageDo) Take() (*model.KthenaChatMessage, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatMessage), nil
	}
}

func (k kthenaChatMessageDo) Last() (*model.KthenaChatMessage, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatMessage), nil
	}
}

func (k kthenaChatMessageDo) Find() ([]*model.KthenaChatMessage, error) {
	result, err := k.DO.Find()
	return result.([]*model.KthenaChatMessage), err
}

func (k kthenaChatMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KthenaChatMessage, err error) {
	buf := make([]*model.KthenaChatMessage, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kthenaChatMessageDo) FindInBatches(result *[]*model.KthenaChatMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kthenaChatMessageDo) Attrs(attrs ...field.AssignExpr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kthenaChatMessageDo) Assign(attrs ...field.AssignExpr) IKthenaChatMessageDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kthenaChatMessageDo) Joins(fields ...field.RelationField) IKthenaChatMessageDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kthenaChatMessageDo) Preload(fields ...field.RelationField) IKthenaChatMessageDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kthenaChatMessageDo) FirstOrInit() (*model.KthenaChatMessage, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatMessage), nil
	}
}

func (k kthenaChatMessageDo) FirstOrCreate() (*model.KthenaChatMessage, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KthenaChatMessage), nil
	}
}

func (k kthenaChatMessageDo) FindByPage(offset int, limit int) (result []*model.KthenaChatMessage, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kthenaChatMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kthenaChatMessageDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kthenaChatMessageDo) Delete(models ...*model.KthenaChatMessage) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kthenaChatMessageDo) withDO(do gen.Dao) *kthenaChatMessageDo {
	k.DO = *do.(*gen.DO)
	return k
}
