// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newServingUsage(db *gorm.DB, opts ...gen.DOOption) servingUsage {
	_servingUsage := servingUsage{}

	_servingUsage.servingUsageDo.UseDB(db, opts...)
	_servingUsage.servingUsageDo.UseModel(&model.ServingUsage{})

	tableName := _servingUsage.servingUsageDo.TableName()
	_servingUsage.ALL = field.NewAsterisk(tableName)
	_servingUsage.PodUID = field.NewString(tableName, "pod_uid")
	_servingUsage.DeploymentID = field.NewString(tableName, "deployment_id")
	_servingUsage.Namespace = field.NewString(tableName, "namespace")
	_servingUsage.ServiceName = field.NewString(tableName, "service_name")
	_servingUsage.UserID = field.NewUint(tableName, "user_id")
	_servingUsage.AccountID = field.NewUint(tableName, "account_id")
	_servingUsage.Resources = field.NewField(tableName, "resources")
	_servingUsage.StartedAt = field.NewTime(tableName, "started_at")
	_servingUsage.ObservedUntil = field.NewTime(tableName, "observed_until")
	_servingUsage.EndedAt = field.NewTime(tableName, "ended_at")
	_servingUsage.LastSettledAt = field.NewTime(tableName, "last_settled_at")
	_servingUsage.BilledPointsTotal = field.NewInt64(tableName, "billed_points_total")
	_servingUsage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_servingUsage.fillFieldMap()

	return _servingUsage
}

type servingUsage struct {
	servingUsageDo servingUsageDo

	ALL               field.Asterisk
	PodUID            field.String
	DeploymentID      field.String
	Namespace         field.String
	ServiceName       field.String
	UserID            field.Uint
	AccountID         field.Uint
	Resources         field.Field
	StartedAt         field.Time
	ObservedUntil     field.Time
	EndedAt           field.Time
	LastSettledAt     field.Time
	BilledPointsTotal field.Int64
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (s servingUsage) Table(newTableName string) *servingUsage {
	s.servingUsageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s servingUsage) As(alias string) *servingUsage {
	s.servingUsageDo.DO = *(s.servingUsageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *servingUsage) updateTableName(table string) *servingUsage {
	s.ALL = field.NewAsterisk(table)
	s.PodUID = field.NewString(table, "pod_uid")
	s.DeploymentID = field.NewString(table, "deployment_id")
	s.Namespace = field.NewString(table, "namespace")
	s.ServiceName = field.NewString(table, "service_name")
	s.UserID = field.NewUint(table, "user_id")
	s.AccountID = field.NewUint(table, "account_id")
	s.Resources = field.NewField(table, "resources")
	s.StartedAt = field.NewTime(table, "started_at")
	s.ObservedUntil = field.NewTime(table, "observed_until")
	s.EndedAt = field.NewTime(table, "ended_at")
	s.LastSettledAt = field.NewTime(table, "last_settled_at")
	s.BilledPointsTotal = field.NewInt64(table, "billed_points_total")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *servingUsage) WithContext(ctx context.Context) IServingUsageDo {
	return s.servingUsageDo.WithContext(ctx)
}

func (s servingUsage) TableName() string { return s.servingUsageDo.TableName() }

func (s servingUsage) Alias() string { return s.servingUsageDo.Alias() }

func (s servingUsage) Columns(cols ...field.Expr) gen.Columns {
	return s.servingUsageDo.Columns(cols...)
}

func (s *servingUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *servingUsage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["pod_uid"] = s.PodUID
	s.fieldMap["deployment_id"] = s.DeploymentID
	s.fieldMap["namespace"] = s.Namespace
	s.fieldMap["service_name"] = s.ServiceName
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["account_id"] = s.AccountID
	s.fieldMap["resources"] = s.Resources
	s.fieldMap["started_at"] = s.StartedAt
	s.fieldMap["observed_until"] = s.ObservedUntil
	s.fieldMap["ended_at"] = s.EndedAt
	s.fieldMap["last_settled_at"] = s.LastSettledAt
	s.fieldMap["billed_points_total"] = s.BilledPointsTotal
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s servingUsage) clone(db *gorm.DB) servingUsage {
	s.servingUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s servingUsage) replaceDB(db *gorm.DB) servingUsage {
	s.servingUsageDo.ReplaceDB(db)
	return s
}

type servingUsageDo struct{ gen.DO }

type IServingUsageDo interface {
	gen.SubQuery
	Debug() IServingUsageDo
	WithContext(ctx context.Context) IServingUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServingUsageDo
	WriteDB() IServingUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServingUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServingUsageDo
	Not(conds ...gen.Condition) IServingUsageDo
	Or(conds ...gen.Condition) IServingUsageDo
	Select(conds ...field.Expr) IServingUsageDo
	Where(conds ...gen.Condition) IServingUsageDo
	Order(conds ...field.Expr) IServingUsageDo
	Distinct(cols ...field.Expr) IServingUsageDo
	Omit(cols ...field.Expr) IServingUsageDo
	Join(table schema.Tabler, on ...field.Expr) IServingUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServingUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServingUsageDo
	Group(cols ...field.Expr) IServingUsageDo
	Having(conds ...gen.Condition) IServingUsageDo
	Limit(limit int) IServingUsageDo
	Offset(offset int) IServingUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServingUsageDo
	Unscoped() IServingUsageDo
	Create(values ...*model.ServingUsage) error
	CreateInBatches(values []*model.ServingUsage, batchSize int) error
	Save(values ...*model.ServingUsage) error
	First() (*model.ServingUsage, error)
	Take() (*model.ServingUsage, error)
	Last() (*model.ServingUsage, error)
	Find() ([]*model.ServingUsage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServingUsage, err error)
	FindInBatches(result *[]*model.ServingUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServingUsage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServingUsageDo
	Assign(attrs ...field.AssignExpr) IServingUsageDo
	Joins(fields ...field.RelationField) IServingUsageDo
	Preload(fields ...field.RelationField) IServingUsageDo
	FirstOrInit() (*model.ServingUsage, error)
	FirstOrCreate() (*model.ServingUsage, error)
	FindByPage(offset int, limit int) (result []*model.ServingUsage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServingUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s servingUsageDo) Debug() IServingUsageDo {
	return s.withDO(s.DO.Debug())
}

func (s servingUsageDo) WithContext(ctx context.Context) IServingUsageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s servingUsageDo) ReadDB() IServingUsageDo {
	return s.Clauses(dbresolver.Read)
}

func (s servingUsageDo) WriteDB() IServingUsageDo {
	return s.Clauses(dbresolver.Write)
}

func (s servingUsageDo) Session(config *gorm.Session) IServingUsageDo {
	return s.withDO(s.DO.Session(config))
}

func (s servingUsageDo) Clauses(conds ...clause.Expression) IServingUsageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s servingUsageDo) Returning(value interface{}, columns ...string) IServingUsageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s servingUsageDo) Not(conds ...gen.Condition) IServingUsageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s servingUsageDo) Or(conds ...gen.Condition) IServingUsageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s servingUsageDo) Select(conds ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s servingUsageDo) Where(conds ...gen.Condition) IServingUsageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s servingUsageDo) Order(conds ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s servingUsageDo) Distinct(cols ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s servingUsageDo) Omit(cols ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s servingUsageDo) Join(table schema.Tabler, on ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s servingUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s servingUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s servingUsageDo) Group(cols ...field.Expr) IServingUsageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s servingUsageDo) Having(conds ...gen.Condition) IServingUsageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s servingUsageDo) Limit(limit int) IServingUsageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s servingUsageDo) Offset(offset int) IServingUsageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s servingUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServingUsageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s servingUsageDo) Unscoped() IServingUsageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s servingUsageDo) Create(values ...*model.ServingUsage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s servingUsageDo) CreateInBatches(values []*model.ServingUsage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s servingUsageDo) Save(values ...*model.ServingUsage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s servingUsageDo) First() (*model.ServingUsage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServingUsage), nil
	}
}

func (s servingUsageDo) Take() (*model.ServingUsage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServingUsage), nil
	}
}

func (s servingUsageDo) Last() (*model.ServingUsage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServingUsage), nil
	}
}

func (s servingUsageDo) Find() ([]*model.ServingUsage, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServingUsage), err
}

func (s servingUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServingUsage, err error) {
	buf := make([]*model.ServingUsage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s servingUsageDo) FindInBatches(result *[]*model.ServingUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s servingUsageDo) Attrs(attrs ...field.AssignExpr) IServingUsageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s servingUsageDo) Assign(attrs ...field.AssignExpr) IServingUsageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s servingUsageDo) Joins(fields ...field.RelationField) IServingUsageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s servingUsageDo) Preload(fields ...field.RelationField) IServingUsageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s servingUsageDo) FirstOrInit() (*model.ServingUsage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServingUsage), nil
	}
}

func (s servingUsageDo) FirstOrCreate() (*model.ServingUsage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServingUsage), nil
	}
}

func (s servingUsageDo) FindByPage(offset int, limit int) (result []*model.ServingUsage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s servingUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s servingUsageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s servingUsageDo) Delete(models ...*model.ServingUsage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *servingUsageDo) withDO(do gen.Dao) *servingUsageDo {
	s.DO = *do.(*gen.DO)
	return s
}
